version: '3'

services: 

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
    volumes:
      - ./requirements.txt:/code/requirements.txt
      - type: bind
        source: "./my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
      - ./db/migrate:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10

  frontend:
    image: node
    volumes:
      - ./frontend:/frontend
    command: ["sh", "-c", "cd frontend && npm install && npm start"]  
    ports:
      - 3000:3000  

  kyopurorecordapp:
    container_name: 'kyopurorecordapp'
    build:
      context: './'
      dockerfile: 'Dockerfile'
    volumes: 
      - './backend:/code/backend'
    ports: 
      - '80:80'
    depends_on:
      mysql:
        condition: service_healthy
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "80"]
